name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: 34.228.40.21
        username: ec2-user
        key: ${{ secrets.sshkey }}
        port: 22
        script: |
          rm -rf cfn-test
          git clone https://github.com/sauravsa21/cfntest.git
          cd cfntest
          sudo docker build -t test .
          sudo docker run -dit --name testc -p 8080:8080 test
