name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: 34.228.40.21
        username: ec2-user
        key: ${{ secrets.sshkey }}
        port: 22
        script: |
          git clone https://github.com:KhandelwalGK/cfntest.git
